#!/bin/sh -e

case "$1" in
    remove)
        systemctl disable --now adguardhome
    ;;

    purge)
        rm -rf /var/opt/adguardhome
        rm -rf /var/log/adguardhome
        rm -f /etc/opt/adguardhome.yaml
    ;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *) echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0
