#!/bin/sh -e

echo "postinst: $@"

case "$1" in
    configure|reconfigure)
        mkdir -p /etc/opt/adguardhome
        mkdir -p /var/opt/adguardhome
        mkdir -p /var/log/adguardhome

        touch /etc/opt/adguardhome/AdGuardHome.yaml

        systemctl daemon-reload
        systemctl enable adguardhome
        systemctl start adguardhome
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac