#!/bin/sh -e

case "$1" in
    configure|reconfigure)
        mkdir -p /var/opt/adguardhome
        mkdir -p /var/log/adguardhome

        [ -f /etc/opt/adguardhome/AdGuardHome.yaml ] && \
          mv /etc/opt/adguardhome/AdGuardHome.yaml /etc/opt/adguardhome.yaml
        rm -rf /etc/opt/adguardhome

        systemctl enable --now adguardhome
        systemctl restart adguardhome
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
